#ifndef USERPARAMETERS
#define USERPARAMETERS

#define OUT_OF_KEY_PENALTY 12
#define SECONDARY_DOMINANT_PENALTY 4
#define MODAL_MIXTURE_PENALTY 4
#define REPEATED_ROOT_PENALTY 4
#define REPEATED_CHORD_PENALTY 12

#endif
